FactoryBot.define do
  factory :machine_learning_job do
    user
    script { "proposal_comments" }
    started_at { Time.current }
    finished_at { nil }
    error { nil }

    dry_run { false }
    total_tokens { 0 }
  end

  factory :ml_summary_comment do
    association :commentable, factory: :proposal
    body { "Summary comment generated by Machine Learning" }
  end

  factory :machine_learning_info do
    kind { "tags" }
    generated_at { Time.current }
    script { "proposal_tags" }
  end
end
